// legacy/Kenneth/angular/hello-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  car = "./assets/kachow.jpeg";
  color = "white"

  changeColor = () => {
    console.log("whoo")
    let colors = ["red", "blue", "green", "yellow", "purple"];
    this.color = colors[Math.floor(Math.random() * 6)];
  };

}

<div class="hello" [ngStyle]="{ 'background-color': this.color }">
  <img class="pic" src="{{ this.car }}" alt="kachow">
  <button class="btn" (click)="changeColor()">Change Background Color</button>
  <a routerLink="/sally" routerLinkActive="active">Sally</a>
</div>
<router-outlet></router-outlet>

// Kenneth/react/hello-react/src/App.js
import React, { Component } from 'react';
import lightning from "./kachow.jpeg";
import './App.css';

class App extends Component {
  state = {
    car: lightning,
    divStyle: {
      backgroundColor: "white"
    }
  };

  changeColor = () => {
    let colors = ["red", "blue", "green", "yellow", "purple"];
    this.setState({
      divStyle: {
        backgroundColor: colors[Math.floor(Math.random() * 6)]
      }
    });
  };

  render() {
    return (
      <div className="hello" style={ this.state.divStyle }>
        <img className="pic" src={ this.state.car } alt="lightning mcqueen"></img>
        <button className="btn" onClick={ this.changeColor }>Change Background Color</button>
      </div>
    );
  }
}

export default App;
